/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SoetchErrorHandler;

public class SEH {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void isAlive() {
        System.out.println("Alive !");
    }

    public static void main(String[] args){
        new SEH();
        isAlive();
    }
}